language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - cask
  - git clone https://code.orgmode.org/bzg/org-mode.git && cd org-mode && git checkout ${ORG} && make autoloads && cd ..
env:
  # I want to use Cask to gather dependencies
  # Cask does not support Emacs 23.
  # Therefore I don't support emacs-23
  # - EMACS=emacs23

  # 8.2.6 fails with (error "`recenter'ing a window that does not display current-buffer.")
  - EVM_EMACS=emacs-25.3-travis ORG=release_8.2.7

  # test latest released emacs and org-mode
  - EVM_EMACS=emacs-25.3-travis ORG=release_9.0.5

  # test oldest supported emacs with minimum supported org-mode
  - EVM_EMACS=emacs-24.3-travis ORG=release_8.2.7

  # test oldest supported emacs with latest released org-mode
  - EVM_EMACS=emacs-24.3-travis ORG=release_9.0.5
script:
  - make test
